# Generated by Django 4.2.15 on 2024-12-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='roll_number',
            new_name='student_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
